# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - unimo

on:
  push:
    branches:
      - test-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b6ef37a269d2481bbd52fcc0cd374487 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_af8e467f55404f46860f66c5814b2ace }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b6ef37a269d2481bbd52fcc0cd374487 }}/nuwansubhasingha/frontend-unimo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'unimo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cb5f01c1df764e049b8e1a3b33419826 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b6ef37a269d2481bbd52fcc0cd374487 }}/nuwansubhasingha/frontend-unimo:${{ github.sha }}'